const data = {
  products: [
    {
      name: "Cheese Pizza Full",
      category: "Shirts",
      image: "/images/cheese.jpg",
      price: 300,
      countInStock: 10,
      brand: "Pizza",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Veg Pizza Full",
      category: "Shirts",
      image: "/images/vegpizza.jpg",
      price: 250,
      countInStock: 20,
      brand: "Adidas",
      rating: 4.0,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Veg Burger",
      category: "Shirts",
      image: "/images/vegburger.jpg",
      price: 80,
      countInStock: 10,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
    },
    {
      name: "Chicken Burger",
      category: "Pants",
      image: "/images/burger.jpg",
      price: 100,
      countInStock: 15,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
    },
    {
      name: "cheese pasta",
      category: "Pants",
      image: "/images/cheesepasta.jpg",
      price: 65,
      countInStock: 5,
      brand: "Puma",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
    },
    {
      name: "Italian pasta",
      category: "Pants",
      image: "/images/italianpasta.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Veg Rolls 2 in plate",
      category: "Pants",
      image: "/images/rolls.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Tomato pasta",
      category: "Pants",
      image: "/images/tomatopasta.jpg",
      price: 85,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    },
    {
      name: "Mexican food",
      category: "Pants",
      image: "/images/mexicanfood.jpg",
      price: 100,
      countInStock: 12,
      brand: "Adidas",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
    }
  ],
};
export default data;
